# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20170807_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='stream_belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.Stream'),
        ),
    ]
