# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20170808_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='cover_img',
            field=models.ImageField(blank=True, upload_to='cover_imgs/'),
        ),
    ]
