# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_stream_cover_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
