# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_auto_20170820_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
