# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_stream_shared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='shared',
            new_name='is_public',
        ),
    ]
